import Link from "next/link";
import {redirect} from "next/navigation";
import {updateBuyerProfileUpdateRequestStatusAction} from "@/actions/createAdminRecords";
import {AdminEmptyState, AdminListToolbar, AdminPagination, AdminResultCount} from "@/components/admin/AdminListControls";
import {AdminStatusPill, adminToneFromStatus} from "@/components/admin/AdminViewControls";
import {adminListHref, adminResultRange, parseAdminPage, parseAdminPageSize} from "@/lib/adminListParams.js";
import {prisma} from "@/lib/prisma";
type Params = Record<string, string | string[] | undefined>;
const statuses = ["New", "Reviewing", "Approved", "Changes applied", "Rejected"];
const text = (raw: string | string[] | undefined) => String(Array.isArray(raw) ? raw[0] : raw || "").trim();
const date = (value: Date) => new Intl.DateTimeFormat("en-GB", {dateStyle: "medium", timeStyle: "short"}).format(value);
const summary = (request: {companyInfo: string | null; buyingProfile: string | null; financeInfo: string | null; contactInfo: string | null; documentsNote: string | null; message: string | null}) => [["Company", request.companyInfo], ["Buying", request.buyingProfile], ["Finance", request.financeInfo], ["Contact", request.contactInfo], ["Documents", request.documentsNote], ["Message", request.message]].filter(([, value]) => value).map(([label]) => label).join(", ") || "No change summary";
export default async function BuyerUpdateRequestsList({raw, pathname = "/admin/buyer-profile-requests", hiddenParams = {}}: {raw: Params; pathname?: string; hiddenParams?: Record<string, string>}) {
  const q = text(raw.q), status = text(raw.status), type = text(raw.type), pageSize = parseAdminPageSize(text(raw.pageSize)), page = parseAdminPage(text(raw.page));
  const where = {...(status ? {status} : {}), ...(type ? {requestType: type} : {}), ...(q ? {OR: [{requestType: {contains: q, mode: "insensitive" as const}}, {message: {contains: q, mode: "insensitive" as const}}, {adminNote: {contains: q, mode: "insensitive" as const}}, {customer: {name: {contains: q, mode: "insensitive" as const}}}]} : {})};
  const [total, statusValues, types] = await Promise.all([prisma.buyerProfileUpdateRequest.count({where}), prisma.buyerProfileUpdateRequest.findMany({distinct: ["status"], select: {status: true}, orderBy: {status: "asc"}}), prisma.buyerProfileUpdateRequest.findMany({distinct: ["requestType"], select: {requestType: true}, orderBy: {requestType: "asc"}})]);
  const pages = Math.max(1, Math.ceil(total / pageSize)), base = {...hiddenParams, q, status, type, pageSize}; if (page > pages) redirect(adminListHref(pathname, base, {page: pages}));
  const requests = await prisma.buyerProfileUpdateRequest.findMany({where, orderBy: [{createdAt: "desc"}, {id: "desc"}], skip: (page - 1) * pageSize, take: pageSize, include: {customer: {select: {id: true, name: true, phone: true, buyerType: true}}}});
  const range = adminResultRange(page, pageSize, total), resetHref = adminListHref(pathname, hiddenParams);
  return <div className="grid gap-4"><AdminListToolbar search={q} pageSize={pageSize} resetHref={resetHref} hiddenParams={hiddenParams} searchLabel="Search update requests" searchPlaceholder="Buyer, request type or notes" filters={[{name: "status", label: "Status", value: status, options: statusValues.map((x) => ({value: x.status, label: x.status}))}, {name: "type", label: "Request type", value: type, options: types.map((x) => ({value: x.requestType, label: x.requestType}))}]}/><AdminResultCount {...range} total={total} label="requests"/>{requests.length ? <div className="grid gap-3">{requests.map((request) => <article key={request.id} className="rounded-2xl border bg-white p-4"><div className="flex justify-between gap-3"><div><Link href={`/admin/customers/${request.customerId}`} className="font-black text-[#1f7a3f]">{request.customer.name}</Link><p className="text-xs text-[#587063]">{request.requestType} · {date(request.createdAt)}</p></div><AdminStatusPill tone={adminToneFromStatus(request.status)}>{request.status}</AdminStatusPill></div><p className="mt-3 text-sm">Requested areas: {summary(request)}</p><details className="mt-3"><summary className="cursor-pointer text-sm font-black">Review</summary><div className="mt-3 grid gap-2 rounded-xl bg-[#f3f8ef] p-3 text-sm">{[["Company", request.companyInfo], ["Buying profile", request.buyingProfile], ["Finance", request.financeInfo], ["Contact", request.contactInfo], ["Documents", request.documentsNote], ["Message", request.message]].map(([label, value]) => value ? <p key={label}><strong>{label}:</strong> {value}</p> : null)}<form action={updateBuyerProfileUpdateRequestStatusAction} className="mt-2 grid gap-2 md:grid-cols-[1fr_2fr_auto]"><input type="hidden" name="requestId" value={request.id}/><select name="status" defaultValue={request.status} className="rounded-lg border bg-white px-3 py-2">{statuses.map((item) => <option key={item}>{item}</option>)}</select><input name="adminNote" defaultValue={request.adminNote || ""} placeholder="Optional review note" className="rounded-lg border px-3 py-2"/><button className="rounded-lg bg-[#1f7a3f] px-3 py-2 font-black text-white">Save</button></form></div></details></article>)}</div> : <AdminEmptyState title="No matching update requests" description="Try another search or clear the filters." resetHref={resetHref}/>}<AdminPagination page={page} totalPages={pages} previousHref={page > 1 ? adminListHref(pathname, base, {page: page - 1}) : undefined} nextHref={page < pages ? adminListHref(pathname, base, {page: page + 1}) : undefined}/></div>;
}
