import Link from "next/link";
import {redirect} from "next/navigation";
import {AdminEmptyState, AdminListToolbar, AdminPagination, AdminResultCount} from "@/components/admin/AdminListControls";
import {AdminStatusPill, adminToneFromStatus} from "@/components/admin/AdminViewControls";
import {adminListHref, adminResultRange, parseAdminPage, parseAdminPageSize} from "@/lib/adminListParams.js";
import {prisma} from "@/lib/prisma";
type Params = Record<string, string | string[] | undefined>;
const text = (raw: string | string[] | undefined) => String(Array.isArray(raw) ? raw[0] : raw || "").trim();
const date = (value: Date) => new Intl.DateTimeFormat("en-GB", {dateStyle: "medium"}).format(value);
const loginState = (buyer: {status: string; accountLoginReady: boolean}) =>
  buyer.status === "Active" && buyer.accountLoginReady
    ? "Approved for login"
    : "Pending login approval";

export default async function BuyersList({raw}: {raw: Params}) {
  const q = text(raw.q), status = text(raw.status), type = text(raw.type), readiness = text(raw.readiness), pageSize = parseAdminPageSize(text(raw.pageSize)), page = parseAdminPage(text(raw.page));
  const where = {...(q ? {OR: [{name: {contains: q, mode: "insensitive" as const}}, {phone: {contains: q}}, {email: {contains: q, mode: "insensitive" as const}}, {location: {contains: q, mode: "insensitive" as const}}]} : {}), ...(status ? {accountStatus: status} : {}), ...(type ? {buyerType: type} : {}), ...(readiness === "ready" ? {accountLoginReady: true} : readiness === "not-ready" ? {accountLoginReady: false} : {})};
  const [total, statuses, types] = await Promise.all([prisma.customer.count({where}), prisma.customer.findMany({distinct: ["accountStatus"], select: {accountStatus: true}, orderBy: {accountStatus: "asc"}}), prisma.customer.findMany({distinct: ["buyerType"], select: {buyerType: true}, orderBy: {buyerType: "asc"}})]);
  const pages = Math.max(1, Math.ceil(total / pageSize)), base = {view: "all", q, status, type, readiness, pageSize};
  if (page > pages) redirect(adminListHref("/admin/customers", base, {page: pages}));
  const buyers = await prisma.customer.findMany({where, orderBy: [{updatedAt: "desc"}, {id: "desc"}], skip: (page - 1) * pageSize, take: pageSize, select: {id: true, name: true, buyerType: true, phone: true, email: true, status: true, accountStatus: true, accountLoginReady: true, updatedAt: true, _count: {select: {orders: true}}}});
  const range = adminResultRange(page, pageSize, total);
  return <div className="grid gap-4"><AdminListToolbar search={q} pageSize={pageSize} resetHref="/admin/customers?view=all" hiddenParams={{view: "all"}} searchLabel="Search buyers" searchPlaceholder="Name, phone, email or location" filters={[{name: "status", label: "Account status", value: status, options: statuses.map((x) => ({value: x.accountStatus, label: x.accountStatus}))}, {name: "type", label: "Buyer type", value: type, options: types.map((x) => ({value: x.buyerType, label: x.buyerType}))}, {name: "readiness", label: "Access readiness", value: readiness, options: [{value: "ready", label: "Login ready"}, {value: "not-ready", label: "Not login ready"}]}]}/><AdminResultCount {...range} total={total} label="buyers"/>{buyers.length ? <><section className="hidden overflow-hidden rounded-2xl border bg-white md:block"><table className="w-full text-left text-sm"><thead className="bg-[#f3f8ef] text-xs uppercase"><tr><th className="p-3">Buyer</th><th className="p-3">Contact</th><th className="p-3">Status</th><th className="p-3">Orders</th><th className="p-3">Last activity</th><th className="p-3">Action</th></tr></thead><tbody>{buyers.map((buyer) => <tr key={buyer.id} className="border-t"><td className="p-3"><p className="font-black">{buyer.name}</p><p className="text-xs text-[#587063]">{buyer.buyerType}</p></td><td className="p-3">{buyer.phone}<p className="text-xs">{buyer.email || "No email"}</p></td><td className="p-3"><AdminStatusPill tone={adminToneFromStatus(loginState(buyer))}>{loginState(buyer)}</AdminStatusPill><p className="mt-1 text-xs">Internal label: {buyer.accountStatus}</p></td><td className="p-3">{buyer._count.orders}</td><td className="p-3">{date(buyer.updatedAt)}</td><td className="p-3"><Link href={`/admin/customers/${buyer.id}`} className="font-black text-[#1f7a3f]">View buyer</Link></td></tr>)}</tbody></table></section><section className="grid gap-3 md:hidden">{buyers.map((buyer) => <article key={buyer.id} className="rounded-2xl border bg-white p-4"><div className="flex justify-between gap-3"><div><h2 className="font-black">{buyer.name}</h2><p className="text-xs">{buyer.buyerType} · {buyer.phone}</p></div><AdminStatusPill tone={adminToneFromStatus(loginState(buyer))}>{loginState(buyer)}</AdminStatusPill></div><p className="mt-3 text-sm">{buyer._count.orders} orders · Internal label: {buyer.accountStatus}</p><Link href={`/admin/customers/${buyer.id}`} className="mt-3 inline-flex font-black text-[#1f7a3f]">View buyer</Link></article>)}</section></> : <AdminEmptyState title="No matching buyers" description="Try another search or clear the filters." resetHref="/admin/customers?view=all"/>}<AdminPagination page={page} totalPages={pages} previousHref={page > 1 ? adminListHref("/admin/customers", base, {page: page - 1}) : undefined} nextHref={page < pages ? adminListHref("/admin/customers", base, {page: page + 1}) : undefined}/></div>;
}
