import Link from "next/link";
import {AdminEmptyState, AdminPagination, AdminResultCount} from "@/components/admin/AdminListControls";
import {AdminStatusPill, adminToneFromStatus} from "@/components/admin/AdminViewControls";
import {adminListHref, adminResultRange, parseAdminPage, parseAdminPageSize} from "@/lib/adminListParams.js";
import {prisma} from "@/lib/prisma";
type Params = Record<string, string | string[] | undefined>;
const text = (raw: string | string[] | undefined) => String(Array.isArray(raw) ? raw[0] : raw || "").trim();
const date = (value: Date | null) => value ? new Intl.DateTimeFormat("en-GB", {dateStyle: "medium"}).format(value) : "Not recorded";
export default async function BuyerAccessList({raw}: {raw: Params}) {
  const q = text(raw.q), status = text(raw.status), role = text(raw.role), pageSize = parseAdminPageSize(text(raw.pageSize)), contactPage = parseAdminPage(text(raw.contactPage)), invitePage = parseAdminPage(text(raw.invitePage));
  const contactWhere = {...(role ? {role} : {}), ...(status ? {status} : {}), ...(q ? {OR: [{name: {contains: q, mode: "insensitive" as const}}, {email: {contains: q, mode: "insensitive" as const}}, {phone: {contains: q}}, {customer: {name: {contains: q, mode: "insensitive" as const}}}]} : {})};
  const inviteWhere = {...(role ? {role} : {}), ...(status ? {status} : {}), ...(q ? {OR: [{email: {contains: q, mode: "insensitive" as const}}, {phone: {contains: q}}, {customer: {name: {contains: q, mode: "insensitive" as const}}}]} : {})};
  const [contactTotal, inviteTotal, contacts, invites] = await Promise.all([
    prisma.buyerContact.count({where: contactWhere}), prisma.buyerAccountInvite.count({where: inviteWhere}),
    prisma.buyerContact.findMany({where: contactWhere, orderBy: [{createdAt: "desc"}, {id: "desc"}], skip: (contactPage - 1) * pageSize, take: pageSize, include: {customer: {select: {id: true, name: true}}}}),
    prisma.buyerAccountInvite.findMany({where: inviteWhere, orderBy: [{createdAt: "desc"}, {id: "desc"}], skip: (invitePage - 1) * pageSize, take: pageSize, include: {customer: {select: {id: true, name: true, updatedAt: true}}}}),
  ]);
  const base = {view: "access", q, status, role, pageSize};
  return <div className="grid gap-5"><section className="rounded-2xl border bg-white p-4"><form className="grid gap-3 md:grid-cols-[2fr_1fr_1fr_auto]"><input type="hidden" name="view" value="access"/><input name="q" defaultValue={q} placeholder="Buyer, contact, email or phone" className="rounded-xl border px-3 py-2"/><input name="status" defaultValue={status} placeholder="Exact status" className="rounded-xl border px-3 py-2"/><input name="role" defaultValue={role} placeholder="Exact role" className="rounded-xl border px-3 py-2"/><button className="rounded-xl bg-[#102015] px-4 py-2 font-black text-white">Apply</button></form></section><div className="flex justify-end"><Link href="/admin/buyer-access" className="rounded-xl bg-[#1f7a3f] px-4 py-2 text-sm font-black text-white">Manage contacts and invites</Link></div><AccessSection title="Authorised contacts" total={contactTotal} range={adminResultRange(contactPage, pageSize, contactTotal)} page={contactPage} pages={Math.max(1, Math.ceil(contactTotal / pageSize))} previous={contactPage > 1 ? adminListHref("/admin/customers", base, {contactPage: contactPage - 1, invitePage}) : undefined} next={contactPage * pageSize < contactTotal ? adminListHref("/admin/customers", base, {contactPage: contactPage + 1, invitePage}) : undefined}>{contacts.map((item) => <AccessRow key={item.id} buyerId={item.customerId} buyer={item.customer.name} contact={item.name} email={item.email} role={item.role} status={item.status} activity={item.createdAt}/>)}</AccessSection><AccessSection title="Account invitations" total={inviteTotal} range={adminResultRange(invitePage, pageSize, inviteTotal)} page={invitePage} pages={Math.max(1, Math.ceil(inviteTotal / pageSize))} previous={invitePage > 1 ? adminListHref("/admin/customers", base, {contactPage, invitePage: invitePage - 1}) : undefined} next={invitePage * pageSize < inviteTotal ? adminListHref("/admin/customers", base, {contactPage, invitePage: invitePage + 1}) : undefined}>{invites.map((item) => <AccessRow key={item.id} buyerId={item.customerId} buyer={item.customer.name} contact={item.phone || "Invite"} email={item.email} role={item.role} status={item.status} activity={item.acceptedAt || item.sentAt || item.createdAt} expiry={item.expiresAt}/>)}</AccessSection></div>;
}
function AccessSection({title, total, range, page, pages, previous, next, children}: {title: string; total: number; range: {start: number; end: number}; page: number; pages: number; previous?: string; next?: string; children: React.ReactNode}) { return <section className="grid gap-3"><h2 className="text-xl font-black">{title}</h2><AdminResultCount {...range} total={total} label="records"/>{total ? <div className="grid gap-3">{children}</div> : <AdminEmptyState title={`No ${title.toLowerCase()}`} description="No matching access records were found."/>}<AdminPagination page={page} totalPages={pages} previousHref={previous} nextHref={next}/></section>; }
function AccessRow({buyerId, buyer, contact, email, role, status, activity, expiry}: {buyerId: string; buyer: string; contact: string; email: string | null; role: string; status: string; activity: Date; expiry?: Date | null}) { return <article className="rounded-2xl border bg-white p-4"><div className="flex justify-between gap-3"><div><Link href={`/admin/customers/${buyerId}?section=access`} className="font-black text-[#1f7a3f]">{buyer}</Link><p className="text-sm">{contact} · {email || "No email"}</p></div><AdminStatusPill tone={adminToneFromStatus(status)}>{status}</AdminStatusPill></div><p className="mt-2 text-xs text-[#587063]">{role} · Latest access activity: {date(activity)}{expiry ? ` · Expires ${date(expiry)}` : ""}</p></article>; }
